[firebase]
type = "service_account"
project_id = "boss-84e2d"
private_key_id = "6718390ce60876289435e1a18691ab1deabd21c3"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDq6pZfCxMXCSjbXeO8pL+KywFvil6C42pqBw5+KVbTAE93arVi6+Dk+z1H5PfFgC1Dm4JBa85EDmK1LcaMujRMM+GirWRZ/ii5Nb7zg4BAs5KPYOIxUk+gZv2/WxatbgCBOBDnUlZbrqCWeZq/TG5XZZyMpiqLZfhFo94ZzYbeLxqiQEduNFS8l+41hdFnkWQPimYrTXdxufaJ9mimWudXBVWtts3n1ZLxOLhNBpwUPIN/EZlPEYxGJ3MCKf96rO9YtnBmWfbIjElG9ejPc6oGFUAQXCwxhdCoVLfF3ZGgYdDngrlwXGQEHflt7knvZI8fBCwSPpzgWxoux4p8+GJzAgMBAAECggEAIsQS+v/llFwrqsNrZ8it/Dls/ffpYs+LOSPQNkWh7to1
6INnUrt77gdsm048iQMeL8o87bepsBK88vlSUBNimAB5nRyyJEtj9X0JxHoqqeipgQSilRAMbr2vQfmWEpacBoOopMNfunPOmlZm23bRQaftEjepRjYSFyRYQ1NSaWEgljuQq2z/yXrMEL5dWUIxPfUEgDbQlKLbcijF5j6PETDo8q1PpIBG6hiLZOo8qBv9am4MlD6V34XKFZ3AFnfCV0IxQb3YON1m6bzsrFUzacBgc3MbIUW5Pj/3KsvxOrXhZ/NxHB4ubX53I89om+t0v1zhLi/qt5iASFUBDH4ZgQKBgQD/1nKzmWMD3oxWCnA3/4qv1TBO8wjB/Hf21zJ6eO3C7a9BprPDQjadbN7T/WaianDOZ6b7WMnbj+4To9q7aJ2+A47bgtKvNLwkWvYJdo5rNYa9Fls9tLlytp8F0yieCVx9PaCTLihVt/DMrD1d
A7scSZ57JGOQmoHdxI9bNXjWQQKBgQDrEL3L0HHk7X89mDbT08fRtOUE5VritnDLR0gBvDwX0/GyRe3xqAZjVaWvD65K1/FOP12NMZxIDgwkjQF9PDch8bZqNe3m+zXLkqiTOALkoEKmCHP/Bt8lby7+PABcHwdUaDfMQ9vHQJDS2YmIqmm9uDA6XQbQADATuBNatiPTswKBgAmTaEWqpxcc/Fm4GE0wRmugaid6V0iTf5YApgYJgrS6GsY1TCMx1kN8MLb0lCPeIgzHumtL/no2X+3iQyyilMzo6y7yLZqbObOOqAjgpCIFJd7r+ExN+Gb/yOH57lpD9W9GoD0CDEZxFRVEGSPjINzFMKZhTUy7S8MWOVtrm/NBAoGBAND8b2F3DutzYz7Fx2kIzoxZAYwaxXTustVnqFMyoVKl8iqHFYdV1WgXS1ia3mBYIIdq
uqe/RayiIJWWb46CLJoXJhDDpaFIEonM9+b7U0ckXFz1AvvnhhjoAqWxfrhoNcILbiBC7HD3rEppcWd56szrpqUc8+OVZykA7OQnLy8VAoGAH1hfsdSLVBzHwQXQ16PEqfXYFsdpCW99RER68XftVxdM77qN9KN7eNxjZ1O53N1+gqeRQeFsW+oko7P6p9dYR0ky07tVy1mYH5Hq/oRu156gc9MJNz3Co0w+tbPz0y7ZjgdjgWC6VEu6QfJp1bNeRSgEi874Mmihvnkr4StdJOQ=
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@boss-84e2d.iam.gserviceaccount.com"
client_id = "109384407308085778884"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40boss-84e2d.iam.gserviceaccount.com"


[cloudinary]
cloud_name = "ddqe5f2br"        
api_key = "531937483944369"
api_secret = "4SHm0oVRaDneYS09YqFny7iJtBg"

[cloudinary_folders]
obras = "control-obras/obras"
